RecipeFormatVersion: 2020-01-25
ComponentName: community.greengrass.nodered
ComponentVersion: 2.1.3
ComponentDescription: Runs Node-RED on a device
ComponentPublisher: Amazon Web Services
ComponentConfiguration:
  DefaultConfiguration:
    headless: "false"
ComponentDependencies: 
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">0.0.0"
  community.greengrass.nodered.auth:
    VersionRequirement: "~1.0.0"
    DependencyType: HARD
Manifests:
  - Lifecycle:
      Install:
        Script: |-
          npm install node-red@2.1.3
          mkdir -p data
          cat > settings.js <<EOF
          module.exports = {
              flowFile: "flows.json",
              flowFilePretty: false,
              userDir: "{work:path}/data",
              uiPort: 1880,
              uiHost: "127.0.0.1",
              logging: {
                  console: {
                      level: "info",
                      metrics: false,
                      audit: false
                  }
              },
              exportGlobalContextKeys: false,
              externalModules: {
              },
              disableEditor: {configuration:/headless},
              editorTheme: {
                  palette: {},
                  projects: {enabled: false, workflow: { mode: "manual" }},
                  codeEditor: {lib: "monaco", options: { theme: "vs", }}
              },

              functionExternalModules: true,
              functionGlobalContext: {
                  // os:require("os"),
              },
              debugMaxLength: 1000,
              mqttReconnectTime: 15000,
              serialReconnectTime: 15000,
          EOF
    
          cat {community.greengrass.nodered.auth:work:path}/auth.js >>settings.js 
          
          echo "}" >> settings.js
      Run:
        Script: |-
          node node_modules/node-red/red.js --settings settings.js

    
